### PR TITLE
Choice Domain Example

### PR DESCRIPTION
**Pull request by philzook58**
A simple example demonstrating the possibility of emulating the Souffle choice-domain feature https://souffle-lang.github.io/choice
The soundness of this representation is still up for debate.

### CODE REVIEW

**Comment by yihozhang** [comment]
Can you define the `const` function using egglog? Something like
```
(function const (Expr Expr) Expr)
(rewrite (const a b) a)
(define choice-function (Expr) Expr :merge (const old new))
```

**Comment by philzook58** [comment]
Oh, interesting. I suppose I can. In my case I was using primitives though. I don't think I can do it over primitives. the `const` table would need to make set and  then discover the rewrite applies. It also materializes the const table. This seems to be a common tradeoff. primitives are kind of a pain in that you need to revert to datalog style programming instead of rewrite style programming, but you don't materialize as much junk.

**Comment by mwillsey** [comment]
You can just say `:merge old`.

**Comment by mwillsey** [comment]
This example seems basically the same as the path examples, so I'm going to close to avoid clutter for now.

**Comment by philzook58** [comment]
Sure. This is demonstrating a different point to the previous path examples. This computes a spanning tree even in the presence of loops in the edge graph. This is unusual for a datalog.

**Pull request closed without merging**
