### PR TITLE
Equational Theory of Sets

### PR DESCRIPTION
**Pull request by philzook58**
Some ideas on an equational theory of sets. WIP

### CODE REVIEW

**Comment by mwillsey** [comment]
We have primitive map now; should we close this?

**Comment by philzook58** [comment]
Does primitive map supports sets of sorts or only sets of primitives? This can hold the former, which I think is still interesting. It also mimics the SMT theory of sets.

**Comment by mwillsey** [comment]
Sure, why not. But it doesn't "respect" the fact that id's might change or merge keys.

**Comment by philzook58** [comment]
Hmm. Is there a mechanism to normalize them via findroot? Would that be possible to add as a primitive? Primitive functions don't have access to the unionfind table so far as I can tell. Perhaps a very special one

**Comment by mwillsey** [comment]
Yeah, idk how to do this. Ideally every sort would be able to canonicalize itself. Perhaps that's the interface... Makes me think that would be useful in general (e.g. polynomials or something).

**Pull request closed without merging**
