### PR TITLE
Add transitive closure benchmark

### PR DESCRIPTION
**Pull request by ezrosent**
Add benchmarks of computing transitive closure for a line graph of varying sizes. This benchmark uses [criterion](https://crates.io/crates/criterion), which does some basic analysis and automatically provides %age changes from the previous run. I've also included ascent on this. Some notes:

* Ascent is a lot faster. Much of that is probably seminaive evaluation, though some could be lack of apples-to-apples in the benchmark setup.
* I excluded parsing from the benchmark measurement but there may be more setup in this crate that is harder to abstract out.
* The default settings for criterion are a little noisy for this workload, it may be worth upping the number of samples collected when using this to track performance improvements or regressions.

Here is the output on my workstation:

```
egg-smol % cargo bench
    Finished bench [optimized] target(s) in 0.06s
     Running unittests src/lib.rs (target/release/deps/egg_smol-430dfd9e678de9d2)

running 1 test
test unionfind::tests::union_find ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/release/deps/egg_smol-6ed0dd50882ca695)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running benches/transitive_closure.rs (target/release/deps/transitive_closure-df58f202aa1c3f5d)
Gnuplot not found, using plotters backend
egg-smol reachability (16 nodes)                                                                            
                        time:   [38.533 ms 39.457 ms 40.420 ms]
                        change: [-3.4828% -0.3234% +2.7868%] (p = 0.84 > 0.05)
                        No change in performance detected.

Benchmarking egg-smol reachability (32 nodes): Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 54.3s, or reduce sample count to 10.
egg-smol reachability (32 nodes)                                                                            
                        time:   [524.39 ms 546.06 ms 567.70 ms]
                        change: [-6.6286% -1.4015% +4.4897%] (p = 0.62 > 0.05)
                        No change in performance detected.

ascent reachability (16 nodes)                                                                             
                        time:   [16.993 µs 17.017 µs 17.043 µs]
                        change: [-1.4958% -1.1670% -0.8478%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 7 outliers among 100 measurements (7.00%)
  1 (1.00%) low mild
  4 (4.00%) high mild
  2 (2.00%) high severe

ascent reachability (32 nodes)                                                                            
                        time:   [62.096 µs 62.174 µs 62.247 µs]
                        change: [-3.0614% -2.6089% -2.1401%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) low mild
  1 (1.00%) high mild
  3 (3.00%) high severe

Benchmarking ascent reachability (1024 nodes): Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 6.1s, or reduce sample count to 80.
ascent reachability (1024 nodes)                                                                            
                        time:   [60.576 ms 60.752 ms 60.942 ms]
                        change: [-0.3604% +0.0423% +0.4630%] (p = 0.84 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  7 (7.00%) high mild
  5 (5.00%) high severe
```

### CODE REVIEW

**Comment by ezrosent** [comment]
I'll mark this as ready for review once #9 is resolved

**Comment by mwillsey** [comment]
Ascent is definitely going to be faster for a while. (1) They have seminaive, and transitive closure is a good use case for that. (2) Our evaluator for terms is more complicated and slower. To catch them, we'd probably have to have some kind of compile step that emits a bytecode or something.

**Comment by ezrosent** [comment]
Thanks! and yeah, I wasn't expecting to match ascent, just figured it'd be useful to have a baseline to compare and ascent is really easy to link into a Rust project like this. Let me know if you'd prefer it to be removed for now.

**Comment by mwillsey** [comment]
Personally, I think we should maybe hold off on benchmarking until we are considering optimizing. I think we are still a little ways off from that. Can you set this back to a draft for now?

**Pull request merged**
