### PR TITLE
Fix #94- query compiler doesn't bind variables that are non canonical

### LINKED ISSUE #94: Parser might mishandle differently-named values constrained to be equal
See the below program.
```
(datatype list
    (Empty)
    (Cons i64 list))

(relation eq (list list))

(eq Empty Empty)

; Oddly, this version works:
; (rule ((= x (Cons x1 rest1)) (= y (Cons x2 rest2)) (= 0 (- x1 x2)) (eq rest1 rest2))
(rule ((= x (Cons x1 rest1)) (= y (Cons x2 rest2)) (= x1 x2) (eq rest1 rest2))
      ((eq (Cons x1 rest1) (Cons x2 rest2))))

(define mylist (Cons 1 Empty))

(run 100)
```

Output:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"i64"`,
 right: `"__bogus__"`', src/typecheck.rs:654:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by oflatt**
This PR fixes #94, #72, and #97, adding them to the tests
It does it by replacing the canonical things in the action. The query compiler is in need of refactor, but this works okay for now.
It also adds a racket script for minimizing egglog programs that throw an error

### CODE REVIEW

**Comment by mwillsey** [comment]
Indeed we need to refactor. Great catch. Can you move minimize under a new scripts directory?

**Comment by oflatt** [comment]
Done!

**Comment by oflatt** [comment]
I'm confused about the failing build, it doesn't fail locally and the error doesn't make sense

**Comment by mwillsey** [comment]
I bet it’s a rust version thing. At some point I think the rust-toolchain
file disappeared for some reason.

**Comment by oflatt** [comment]
This one?
https://github.com/mwillsey/egg-smol/blob/564cfcfaec26b5bcd868da446623b837902d305d/rust-toolchain

**Comment by mwillsey** [comment]
Yeah, I’m guessing that CI uses an older rust if you don’t tell it
otherwise.

**Comment by oflatt** [comment]
Err, actually I still have that file. Should I bump it?
It's also fishy that I didn't change the rust code but it failed the second time. I'll try rerunning

**Comment by mwillsey** [comment]
I just committed a new version of that file pinning us to 1.66.1, but that
didn't fix the issue. I fixed it just by changing the code.

**Comment by oflatt** [comment]
Okie dokie
Should we merge this then?

**Pull request merged**
